---
- hosts: all
  become: true

  tasks:
  
    - name: Prune everything
      community.docker.docker_prune:
        containers: true
        images: true
        networks: true
        volumes: true
