---
- hosts: all
  become: true

  tasks:
  
    - name: Prune everything
      community.docker.docker_prune:
        containers: true
        images: true
        networks: true
        volumes: true
      register: prune_result
        
    - name: Display the reclaimed space
      debug:
        msg: "Pruned {{ prune_result.containers | length }} containers, {{ prune_result.images | length }} images, {{ prune_result.networks | length }} networks, and {{ prune_result.volumes | length }} volumes."
